"""changed schema of Ingredients, added protein

Revision ID: 9a0f7f572088
Revises: a81f01a260e1
Create Date: 2023-10-26 16:48:44.260530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0f7f572088'
down_revision = 'a81f01a260e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_carbs', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_protein', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_fat', sa.Float(), nullable=True))
        batch_op.drop_column('recipe_quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_quantity', sa.INTEGER(), nullable=True))
        batch_op.drop_column('total_fat')
        batch_op.drop_column('total_protein')
        batch_op.drop_column('total_carbs')

    # ### end Alembic commands ###
