"""added new column to ingredients table

Revision ID: a81f01a260e1
Revises: 56d8d81f0a2b
Create Date: 2023-10-25 15:27:19.524397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81f01a260e1'
down_revision = '56d8d81f0a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('recipe_quantity')

    # ### end Alembic commands ###
